version: "2"
checks:
  file-lines:
    enabled: false
  similar-code:
    enabled: false
  method-complexity:
    enabled: false
  method-lines:
    enabled: false
ratings:
  paths:
  - "**.js"
plugins:
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
